const breedGroupID = {
  'affenpinscher': 1, // Map breed name 'a' to breed_id 1
  'Afghan Hound': 2, // Map breed name 'c' to breed_id 2
  'african hunting dog': 3,
  'airedale terrier': 4,
  'akbash dog': 5,
  'akita': 6,
  'alapaha blue blood bulldog': 7,
  'alaskan husky': 8,
  'alaskan malamute': 9,
  'american bulldog': 10,
  'american bully': 11,
  'american eskimo dog': 12,
  'american eskimo dog (miniature)': 13,
  'american foxhound': 14,
  'american pit bull terrier': 15,
  'american staffordshire terrier': 16,
  'american water spaniel': 17,
  'anatolian shepherd dog': 18,
  'appenzeller sennenhund': 19,
  'australian cattle dog': 21,
  'australian kelpie': 22,
  'australian shepherd': 23,
  'australian terrier': 24,
  'azawakh': 25,
  'barbet': 26,
  'basenji': 28,
  'basset bleu de gascoigne': 29,
  'basset hound': 30,
  'beagle': 31,
  'bearded collie': 32,
  'beauceron': 33,
  'bedlington terrier': 34,
  'belgian malinois': 36,
  'belgian tervuren': 38,
  'bernese mountain dog': 41,
  'bichon frise': 42,
  'black and tan coonhound': 43,
  'bloodhound': 45,
  'bluetick coonhound': 47,
  'boerboel': 48,
  'border collie': 50,
  'border terrier': 51,
  'boston terrier': 53,
  'bouvier des flandres': 54,
  'boxer': 55,
  'boykin spaniel': 56,
  'bracco italiano': 57,
  'briard': 58,
  'brittany': 59,
  'bull terrier': 61,
  'bull terrier (miniature)': 62,
  'bullmastiff': 64,
  'cairn terrier': 65,
  'cane corso': 67,
  'cardigan welsh corgi': 68,
  'catahoula leopard dog': 69,
  'caucasian shepherd (ovcharka)': 70,
  'cavalier king charles spaniel': 71,
  'chesapeake bay retriever': 76,
  'chinese crested': 78,
  'chinese shar-pei': 79,
  'chinook': 80,
  'chow chow': 81,
  'clumber spaniel': 84,
  'cocker spaniel': 86,
  'cocker spaniel (american)': 87,
  'coton de tulear': 89,
  'dalmatian': 92,
  'doberman pinscher': 94,
  'dogo argentino': 95,
  'dutch shepherd': 98,
  'english setter': 101,
  'english shepherd': 102,
  'english springer spaniel': 103,
  'english toy spaniel': 104,
  'english toy terrier': 105,
  'eurasier': 107,
  'field spaniel': 108,
  'finnish lapphund': 110,
  'finnish spitz': 111,
  'french bulldog': 113,
  'german pinscher': 114,
  'german shepherd dog': 115,
  'german shorthaired pointer': 116,
  'giant schnauzer': 119,
  'glen of imaal terrier': 120,
  'golden retriever': 121,
  'gordon setter': 123,
  'great dane': 124,
  'great pyrenees': 125,
  'greyhound': 127,
  'griffon bruxellois': 128,
  'harrier': 129,
  'havanese': 130,
  'irish setter': 134,
  'irish terrier': 135,
  'irish wolfhound': 137,
  'italian greyhound': 138,
  'japanese chin': 140,
  'japanese spitz': 141,
  'keeshond': 142,
  'komondor': 144,
  'kooikerhondje': 145,
  'kuvasz': 147,
  'labrador retriever': 149,
  'lagotto romagnolo': 151,
  'lancashire heeler': 153,
  'leonberger': 155,
  'lhasa apso': 156,
  'maltese': 161,
  'miniature american shepherd': 165,
  'miniature pinscher': 167,
  'miniature schnauzer': 168,
  'newfoundland': 171,
  'norfolk terrier': 172,
  'norwich terrier': 176,
  'nova scotia duck tolling retriever': 177,
  'old english sheepdog': 178,
  'olde english bulldogge': 179,
  'papillon': 181,
  'pekingese': 183,
  'pembroke welsh corgi': 184,
  'perro de presa canario': 185,
  'pharaoh hound': 188,
  'plott': 189,
  'pomeranian': 193,
  'poodle (miniature)': 196,
  'poodle (toy)': 197,
  'pug': 201,
  "puli": 204,
  "pumi": 205,
  "rat terrier": 207,
  "redbone coonhound": 208,
  "rhodesian ridgeback": 209,
  "rottweiler": 210,
  "russian toy": 211,
  "saint bernard": 212,
  "saluki": 213,
  "samoyed": 214,
  "schipperke": 216,
  "scottish deerhound": 218,
  "scottish terrier": 219,
  "shetland sheepdog": 221,
  "shiba inu": 222,
  "shih tzu": 223,
  "shiloh shepherd": 225,
  "siberian husky": 226,
  "silky terrier": 228,
  "smooth fox terrier": 232,
  "soft coated wheaten terrier": 233,
  "spanish water dog": 235,
  "spinone italiano": 236,
  "staffordshire bull terrier": 238,
  "standard schnauzer": 239,
  "swedish vallhund": 242,
  "thai ridgeback": 243,
  "tibetan mastiff": 244,
  "tibetan spaniel": 245,
  "tibetan terrier": 246,
  "toy fox terrier": 248,
  "treeing walker coonhound": 250,
  "vizsla": 251,
  "weimaraner": 253,
  'welsh springer spaniel': 254,
  'west highland white terrier': 256,
  'whippet': 257,
  'white shepherd': 258,
  'wire fox terrier': 259,
  'wirehaired pointing griffon': 260,
  'wirehaired vizsla': 261,
  'xoloitzcuintli': 262,
  'yorkshire terrier': 264
};

export default breedGroupID;